In [1]:
import numpy as np

In [10]:
liste = [[1,2,3],[4,5,6],[7,8,9]]

In [11]:
liste

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [13]:
matrix = np.array(liste)

In [14]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
matrix[2][2]
matrix[2,2]  #bu ikisi aynı şey

np.int64(9)

In [22]:
matrix[0]

array([1, 2, 3])

In [25]:
matrix[1:,2] #satırda 1 ve 1'den sonrasını getir sutunda 2 indexli sutunu getir

array([6, 9])

In [26]:
matrix[0:,2]

array([3, 6, 9])

In [27]:
matrix[1:,1:]

array([[5, 6],
       [8, 9]])

In [28]:
liste2 = np.arange(25).reshape(5,5)

In [29]:
liste2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [30]:
liste2[2]

array([10, 11, 12, 13, 14])

In [32]:
liste2[[0,2,4]] #sıfır iki ve dort indexli satirlari getirir

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])