In [1]:
import numpy as np

Numpy array

In [2]:
benimListem = [20,30,40,50] #normal bir liste

In [3]:
np.array(benimListem) #numpy listesine çevirdik

array([20, 30, 40, 50])

In [4]:
matrixListesi = [[1,2,3],[2,3,4],[3,4,5]]

In [5]:
matrixListesi[0]

[1, 2, 3]

In [6]:
matrixListesi[1]

[2, 3, 4]

In [7]:
matrixListesi[2]

[3, 4, 5]

In [8]:
matrixListesi[0][1]

2

In [9]:
np.array(matrixListesi)

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

# **Arange**

In [10]:
np.arange(0,10) #numpy dizisi oluşturur arange(start,stop,step)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [12]:
np.arange(0,10,3)

array([0, 3, 6, 9])

# Zeros

In [17]:
np.zeros(3) #sıfırlardan oluşan bir numpy array

array([0., 0., 0.])

In [18]:
np.zeros((2,2)) #sıfırlardan oluşan bir numpy matrix np.zeros((satirSayisi,sutunSayisi))

array([[0., 0.],
       [0., 0.]])

# Ones

In [19]:
np.ones(3)

array([1., 1., 1.])

In [21]:
np.ones((4,2)) #birlerden oluşan numpy matrix np.ones((satirSayisi,sutunSayisi))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

# linspace

In [23]:
np.linspace(0,20,5) #aralığı 5 eşit parçaya boler

array([ 0.,  5., 10., 15., 20.])

In [24]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [26]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

# eye

In [28]:
np.eye(3) #birim matris oluşturur identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

# Random

In [32]:
np.random.randn(4) #x elemanlı random bir numpy array oluşturur

array([ 1.22468365, -0.56169776,  2.41447321, -0.1080314 ])

In [35]:
np.random.randn(3,3) #matrix hali

array([[ 1.27231945,  2.47141245,  0.30769895],
       [ 0.94135074,  1.07549469, -0.36616167],
       [-0.70745218,  0.51888589, -0.43686819]])

In [39]:
np.random.randint(1,10) #bu aralıkta integer değer oluşturur randint(başlangıc,bitis) bitis dahil değil

9

In [41]:
np.random.randint(1,10,5) #randint(bas,son,kac eleman) 1 ile 9 arasında 5 elemanlı bir array

array([4, 3, 1, 3, 7])

In [42]:
benimNumpyDizim = np.arange(20)

In [43]:
benimNumpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [44]:
benimRandomDizim = np.random.randint(1,10,10)

In [46]:
benimRandomDizim

array([5, 5, 3, 2, 7, 8, 1, 3, 3, 7])

# Numpy dizi methodları

In [48]:
dizi = np.arange(20)

In [50]:
dizi.reshape(4,5) #yeniden şekillendirme yapar 4 satir 5 sutun

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [52]:
dizi.max() #arraydaki max deger

np.int64(19)

In [54]:
dizi.min() #arraydaki min deger

np.int64(0)

In [56]:
dizi.argmax() #max değerin hangi indexte oldugu

np.int64(19)

In [60]:
dizi.argmin() #min degerin hangi indexte oldugu

np.int64(0)

In [64]:
dizi.shape #dizinin kac satir ve sutun oldugunu ogrenmek icin kullanılır

(20,)