In [1]:
import numpy as np

In [2]:
dizi = np.arange(0,15)

In [3]:
dizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
print(dizi[5])

5


In [11]:
dizi[3:5] #arr[start:stop] stop dahil değil aralıktaki değerleri getir

array([3, 4])

In [14]:
dizi[3:8] = -5 #bu aralıktaki değerleri -5 yapar

In [15]:
dizi

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [16]:
dizi2 = np.arange(0,24)

In [17]:
dizi2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [34]:
slicingDizi = dizi2[4:9]

In [35]:
slicingDizi

array([4, 5, 6, 7, 8])

In [38]:
slicingDizi[:] = 700 #tüm değerleri 700 yapar

In [39]:
slicingDizi

array([700, 700, 700, 700, 700])

In [42]:
dizi2 #slicingDiziyi değiştirmeme rağmen dizi2'de değişti

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [43]:
dizi3 = np.arange(0,24)

In [46]:
dizi3Kopyasi = dizi3[0:8].copy() #ana dizi üzerinde değişiklik olmasını istemiyorsak copy() alıp onun üzerinden değişiklik yapabiliriz

In [51]:
dizi3Kopyasi[:] = -1

In [52]:
dizi3Kopyasi

array([-1, -1, -1, -1, -1, -1, -1, -1])

In [49]:
dizi3 #kopya üzerinden değiştirme yaptığım icin ana dizi de değişme olmadı

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])