In [1]:
import numpy as np

In [9]:
dizi = np.random.randint(1,100,20)

In [10]:
dizi

array([96, 40, 96, 46, 97, 32, 80, 19, 44, 95, 20, 37, 95, 57, 98, 29, 26,
       88, 60, 12])

In [12]:
sonucDizisi = dizi > 24

In [13]:
dizi[sonucDizisi]

array([96, 40, 96, 46, 97, 32, 80, 44, 95, 37, 95, 57, 98, 29, 26, 88, 60])

In [17]:
dizi[dizi > 90]

array([96, 96, 97, 95, 95, 98])

In [20]:
sonDizi = np.arange(0,10)

In [21]:
sonDizi

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
sonDizi + sonDizi #her bir index'i kendisine denk gelen index ile topluyor

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [24]:
sonDizi*sonDizi

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [25]:
sonDizi - sonDizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
sonDizi / sonDizi #sıfır bolu sıfıra nan atar

/tmp/ipykernel_568/1312094733.py:1: RuntimeWarning: invalid value encountered in divide
  sonDizi / sonDizi


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [28]:
np.sqrt(sonDizi) #karekok alır

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])